name: Coleta Horaria
on:
  schedule:
    - cron: '0 * * * *' # Isso faz o robô rodar no minuto 0 de cada hora
  workflow_dispatch:      # Isso cria um botão para você rodar manualmente quando quiser

jobs:
  run-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo do GitHub
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Bibliotecas
        run: pip install requests pandas python-dateutil

      - name: Executar Script de Chuva
        env:
          LICOR_TOKEN: ${{ secrets.LICOR_TOKEN }}
        run: python main.py

      - name: Salvar Arquivos Gerados
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "Bot Coletor"
          git add dados_chuva/*.csv
          git commit -m "Coleta automatica: $(date)" || exit 0
          git push
