- name: Salvar Dados no Historico
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "Bot Engenheiro"
          git pull origin main # Garante que ele pegue o arquivo atualizado antes de salvar
          git add historico_estacao.csv
          git commit -m "Update master data: $(date)" || exit 0
          git push
